/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicol
 */
public class classe extends javax.swing.JFrame {
    
    Connecter cnx = new Connecter ();
    Statement stmt;
    ResultSet rset;
    DefaultTableModel model = new DefaultTableModel ();

    /**
     * Creates new form classe
     */
    public classe() {
        initComponents();
    model.addColumn("classeID");
    model.addColumn("nom");
    model.addColumn("ecoleID");
    model.addColumn("niveauID");
    model.addColumn("id");

    try{
        stmt=cnx.obtenirconnexion().createStatement();
        remplibox();
        remplibox1();
        remplibox2();
        ResultSet Rs=stmt.executeQuery("");
        while(Rs.next()){
            model.addRow(new Object[]{Rs.getString("classeID"),Rs.getString("nom"),Rs.getString("ecoleID"),
            Rs.getString("niveauID"),Rs.getString("id")});
        }
        
    }catch(Exception e){System.err.println(e);}
    
    table.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        txtni = new javax.swing.JComboBox<>();
        txti = new javax.swing.JComboBox<>();
        txte = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtrech = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("nom");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 110, 90, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("ecoleID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 170, 70, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("niveauID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 210, 70, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("id");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 260, 70, 30);

        txtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnActionPerformed(evt);
            }
        });
        jPanel1.add(txtn);
        txtn.setBounds(140, 110, 70, 30);

        txtni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtniMouseEntered(evt);
            }
        });
        txtni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtniActionPerformed(evt);
            }
        });
        jPanel1.add(txtni);
        txtni.setBounds(140, 210, 80, 30);

        txti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtiMouseEntered(evt);
            }
        });
        txti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiActionPerformed(evt);
            }
        });
        jPanel1.add(txti);
        txti.setBounds(140, 260, 80, 30);

        txte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txteMouseEntered(evt);
            }
        });
        txte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteActionPerformed(evt);
            }
        });
        jPanel1.add(txte);
        txte.setBounds(140, 160, 80, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("classeID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 60, 90, 20);

        txtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcActionPerformed(evt);
            }
        });
        jPanel1.add(txtc);
        txtc.setBounds(140, 50, 70, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(81, 48, 290, 300);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(47, 360, 90, 30);

        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(187, 360, 90, 30);

        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(327, 360, 100, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Modifier/ Ajouter / Supprimer les informations d'une classe");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(157, 0, 570, 40);

        jButton4.setText("Rechercher (nom)");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(347, 80, 170, 30);
        getContentPane().add(txtrech);
        txtrech.setBounds(577, 80, 90, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "enseignementID", "classeID", "disciplineID", "personneID"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(410, 170, 910, 140);

        quitter.setText("Quitter");
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });
        getContentPane().add(quitter);
        quitter.setBounds(697, 370, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deplace (int i){
    try{
      txtc.setText(model.getValueAt(i,0).toString());  
      txtn.setText(model.getValueAt(i,1).toString()); 
      txte.setSelectedItem(model.getValueAt(i,2).toString()); 
      txtni.setSelectedItem(model.getValueAt(i,3).toString()); 
      txti.setSelectedItem(model.getValueAt(i,4).toString()); 
      
    }catch (Exception e){System.err.println(e);
    JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getLocalizedMessage());}
}
    private void txtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnActionPerformed

    private void txtniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtniMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtniMouseClicked

    private void txtniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtniMouseEntered

    }//GEN-LAST:event_txtniMouseEntered

    private void txtniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtniActionPerformed

    }//GEN-LAST:event_txtniActionPerformed

    private void txtiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiMouseClicked

    private void txtiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtiMouseEntered

    }//GEN-LAST:event_txtiMouseEntered

    private void txtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiActionPerformed

    }//GEN-LAST:event_txtiActionPerformed

    private void txteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txteMouseClicked

    private void txteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txteMouseEntered

    }//GEN-LAST:event_txteMouseEntered

    private void txteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteActionPerformed

    }//GEN-LAST:event_txteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String classeID=txtc.getText();
        String nom=txtn.getText();
        String ecoleID=txte.getSelectedItem().toString();
        String niveauID=txtni.getSelectedItem().toString();
        String id=txti.getSelectedItem().toString();

        /*String requete = "INSERT INTO trimestre(ID_tri,numero,debut,fin,id)+ VALUES('"
        +id_tri+"','"+numero+"','"+debut+"','"+fin+"','"+id+"')"; */
        try{
            stmt.executeUpdate("INSERT INTO classe(classeID,nom,ecoleID,niveauID,id)VALUES('"+
                classeID+"','"+nom+"','"+ecoleID+"','"+niveauID+"','"+id+"');");
            JOptionPane.showMessageDialog(null,"La classe a bien été ajoutée");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            if(txtc.getText().length() != 0){
                stmt.executeUpdate("Delete From classe where classeID ="+txtc.getText());
                JOptionPane.showMessageDialog(null,"La classe a bien été supprimée");
            }
            else{JOptionPane.showMessageDialog(null,"Veuillez remplir le champ : ");}
        }catch(Exception e){JOptionPane.showMessageDialog(null,"erreur dans la suppression");}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            stmt.executeUpdate("UPDATE enseignement SET nom='"+txtn.getText()+"',"
                + "ecoleID='"+txte.getSelectedItem().toString()+"',niveauID='"+txtni.getSelectedItem().toString()+"',id='"+txti.getSelectedItem().toString()+"' WHERE enseignementID= "+txtn.getText());
            JOptionPane.showMessageDialog(null,"La classe a bien été modifiée");

        }catch (Exception e){JOptionPane.showMessageDialog(null,"erreur de modification");
            System.err.println(e);}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            model.setRowCount(0);
            {
                rset = stmt.executeQuery("Select * From classe WHERE nom = '"+txtrech.getText()+"'");
            }while(rset.next()){
                Object[] classe = {rset.getString(1),rset.getString(2),rset.getString(3),rset.getString(4),rset.getString(5)};
                model.addRow(classe);
            }

            if (model.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"Il n'y a pas de classe correspondant a votre recherche");
            }

        }catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de recherche");}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try{
            int i =table.getSelectedRow();
            deplace(i);

        } catch(Exception e){JOptionPane.showMessageDialog(null,"erreur avec le tableau");}
    }//GEN-LAST:event_tableMouseClicked

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
        if(evt.getSource()==quitter)
        {
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_quitterActionPerformed

    private void txtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcActionPerformed

    public void remplibox(){
         String sql = "Select id from anneescolaire";
       try{
           ResultSet Rs=stmt.executeQuery(sql);
           while(Rs.next()){
               String id = Rs.getString("id");
               
               txti.addItem(id);
               
           }
           
       }catch (SQLException e){
           e.printStackTrace();
       }
            // TODO add your handling code here:
     }
    
    public void remplibox1(){
         String sql = "Select ecoleID, nom_ecole from ecole";
       try{
           ResultSet Rs=stmt.executeQuery(sql);
           while(Rs.next()){
               String ecoleID = Rs.getString("ecoleID");
               String nom_ecole = Rs.getString("nom_ecole");
               txte.addItem(ecoleID);
               txte.addItem(nom_ecole);
           }
           
       }catch (SQLException e){
           e.printStackTrace();
       }
            // TODO add your handling code here:
     }
    
    public void remplibox2(){
         String sql = "Select niveauID, nom from niveau";
       try{
           ResultSet Rs=stmt.executeQuery(sql);
           while(Rs.next()){
               String niveauID = Rs.getString("niveauID");
               String nom = Rs.getString("nom");
               txtni.addItem(niveauID);
               txtni.addItem(nom);
           }
           
       }catch (SQLException e){
           e.printStackTrace();
       }
            // TODO add your handling code here:
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(classe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(classe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(classe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(classe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new classe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton quitter;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtc;
    private javax.swing.JComboBox<String> txte;
    private javax.swing.JComboBox<String> txti;
    private javax.swing.JTextField txtn;
    private javax.swing.JComboBox<String> txtni;
    private javax.swing.JTextField txtrech;
    // End of variables declaration//GEN-END:variables
}
