/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajur
 */
public class Trimestre extends javax.swing.JFrame {

    /**
     * Creates new form Trimestre
     */
    Connecter cnx = new Connecter ();
    Statement stmt;
    ResultSet rset;
    DefaultTableModel model = new DefaultTableModel ();
    
    public Trimestre() {
        initComponents();
        
    model.addColumn("IDtrimestre");
    model.addColumn("numero");
    model.addColumn("debut");
    model.addColumn("fin");
    model.addColumn("id");
    try{
        stmt=cnx.obtenirconnexion().createStatement();
        ResultSet Rs=stmt.executeQuery("");
        while(Rs.next()){
            model.addRow(new Object[]{Rs.getString("IDtrimestre"),Rs.getString("numero"),Rs.getString("debut"),
            Rs.getString("fin"),Rs.getString("id")});
        }
        
    }catch(Exception e){System.err.println(e);}
    
    table.setModel(model);
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtidt = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        txtdebut = new javax.swing.JTextField();
        txtfin = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtrech = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("IDtrimestre : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 40, 90, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("numero : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 80, 70, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("debut : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 130, 50, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("fin : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 190, 25, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("id : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 240, 63, 14);

        txtidt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidtActionPerformed(evt);
            }
        });
        jPanel1.add(txtidt);
        txtidt.setBounds(120, 30, 70, 30);
        jPanel1.add(txtnumero);
        txtnumero.setBounds(120, 80, 70, 30);
        jPanel1.add(txtdebut);
        txtdebut.setBounds(120, 130, 70, 30);
        jPanel1.add(txtfin);
        txtfin.setBounds(120, 190, 70, 30);
        jPanel1.add(txtid);
        txtid.setBounds(120, 240, 70, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 70, 290, 300);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 400, 80, 23);

        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 400, 80, 23);

        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 390, 100, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Modifier/ Ajouter / Supprimer les informations d'un Trimestre");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 30, 490, 40);

        jButton4.setText("Rechercher");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(400, 110, 100, 30);
        getContentPane().add(txtrech);
        txtrech.setBounds(560, 110, 90, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(400, 200, 320, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void deplace (int i){
    try{
      txtidt.setText(model.getValueAt(i,0).toString());  
      txtnumero.setText(model.getValueAt(i,1).toString()); 
      txtdebut.setText(model.getValueAt(i,2).toString()); 
      txtfin.setText(model.getValueAt(i,3).toString()); 
      txtid.setText(model.getValueAt(i,4).toString()); 
    }catch (Exception e){System.err.println(e);
    JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getLocalizedMessage());}
}
    private void txtidtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
           if(txtidt.getText().length() != 0){
               stmt.executeUpdate("Delete From trimestre where IDtrimestre ="+txtidt.getText());
               JOptionPane.showMessageDialog(null,"Le trimestre a bien été supprimé");
           }
           else{JOptionPane.showMessageDialog(null,"Veuillez remplir le champ : ");}
       }catch(Exception e){JOptionPane.showMessageDialog(null,"erreur dans la suppression");}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String IDtrimestre=txtidt.getText();
        String numero=txtnumero.getText();
        String debut=txtdebut.getText();
        String fin=txtfin.getText();
        String id=txtid.getText();
        /*String requete = "INSERT INTO trimestre(ID_tri,numero,debut,fin,id)+ VALUES('"
                +id_tri+"','"+numero+"','"+debut+"','"+fin+"','"+id+"')"; */
        try{
            stmt.executeUpdate("INSERT INTO trimestre(IDtrimestre,numero,debut,fin,id)VALUES('"+
                    IDtrimestre+"','"+numero+"','"+debut+"','"+fin+"','"+id+"');");
            JOptionPane.showMessageDialog(null,"Le trimestre a bien été ajouté");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
               stmt.executeUpdate("UPDATE trimestre SET numero='"+txtnumero.getText()+"',"
                       + "debut='"+txtdebut.getText()+"',fin='"+txtfin.getText()+"',"
                      + "id='"+txtid.getText()+"' WHERE IDtrimestre= "+txtidt.getText());
               JOptionPane.showMessageDialog(null,"Le trimestre a bien été modifié");
               
        }catch (Exception e){JOptionPane.showMessageDialog(null,"erreur de modification");
        System.err.println(e);}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try{
                int i =table.getSelectedRow();
                deplace(i);
                
        } catch(Exception e){JOptionPane.showMessageDialog(null,"erreur avec le tableau");}         
    }//GEN-LAST:event_tableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            model.setRowCount(0);
            {
                rset = stmt.executeQuery("Select * From trimestre WHERE IDtrimestre = '"+txtrech.getText()+"'");
            }while(rset.next()){
                Object[] trimestre = {rset.getString(1),rset.getString(2),rset.getString(3),rset.getString(4),rset.getString(5)};
                model.addRow(trimestre);
             }
            if (model.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"Il n'y a pas de trimestre correspondant a votre recherche");
            }
            
            
        }catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de recherche");}
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trimestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trimestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trimestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trimestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trimestre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtdebut;
    private javax.swing.JTextField txtfin;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidt;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtrech;
    // End of variables declaration//GEN-END:variables
}
